### ISSUE TITLE
Issue in connecting Buzz to Raspberry Pi via Bleak

### ISSUE THREAD

**Issue by dhruvmsheth** [neosensory/neosensory-sdk-for-python#2]
I followed the instructions provided in the repo, installed the `neosensory-python` library and had the additional packages installed. Thereafter,I connected the Neosensory buzz to the Raspberry Pi 4 using Bluetooth and had it paired. 

After this, when I run the `buzz_a_buzz.py` script, it gives me this error - 
```shell
(venv2) pi@raspberrypi:~/neosensory-sdk-for-python/examples $ python3 buzz_a_buzz.py 
Found a Buzz! D8:4A:B7:23:4A:40: BuzzD84AB7234A40
Address substring: D8:4A:B7:23:4A:40
buzz_a_buzz.py:29: FutureWarning: is_connected has been changed to a property. Calling it as an async method will be removed in a future version
  x = await client.is_connected()
Connection State: True

auth as developer
Traceback (most recent call last):
  File "buzz_a_buzz.py", line 59, in <module>
    loop.run_until_complete(run(loop))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "buzz_a_buzz.py", line 38, in run
    await my_buzz.accept_developer_api_terms()
  File "/home/pi/neosensory-sdk-for-python/neosensory_python/__init__.py", line 62, in accept_developer_api_terms
    await self.client.write_gatt_char(ns_uart_rx_id, cmd)
  File "/home/pi/venv2/lib/python3.7/site-packages/bleak-0.11.0-py3.7.egg/bleak/backends/bluezdbus/client.py", line 812, in write_gatt_char
    assert_reply(reply)
  File "/home/pi/venv2/lib/python3.7/site-packages/bleak-0.11.0-py3.7.egg/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name)
bleak.exc.BleakDBusError: org.bluez.Error.NotPermitted
```
Initially I thought this might be a `virtual environment` error, so I tried without a `venv`, but the error didn't change.
I also tried replacing `x` with the Buzz address, but it continued returning this error. I had in prior configured the Buzz with Android, and it works perfect. So I thought this might be etiher the Raspberry Pi BLE Connectivity issue. So after some searching, I also installed the latest Raspberry Pi BlueZ firmware, to see if it solves the issue. `sudo apt install bluez-firmware`. So I tried interfacing Raspberry Pi with Buzz via BlueZ, and it worked fine. -

```shell
(venv2) pi@raspberrypi:~/neosensory-sdk-for-python/examples $ bluetoothctl
Agent registered
[bluetooth]# scan on
Discovery started
[CHG] Controller DC:A6:32:C4:C3:60 Discovering: yes
[CHG] Device D8:4A:B7:23:4A:40 RSSI: -67
[CHG] Device D8:4A:B7:23:4A:40 RSSI: -59
```

After this the error still remained. Any solutions for this?

**Comment by GreatScott** [comment]
Hmm...this is working for me on a RPi4b with stock Raspberry Pi OS, which I just installed from scratch. I'm able to keep a stable connection with the buzzing pattern from the buzz_a_buzz example. Didn't need to install anything like the BlueZ firmware. 

Based on your description/logs, it looks like everything is correct, though you're running a newer version of bleak than I am

Here's what I did to get it running:
- did not use venv either
- I installed from source (did not use pip)
- To install the SDK, I ran `python3 setup.py develop` 
- Python version running on Pi: 3.7.3
- Bleak version: 0.10.0 (it looks like you have 0.11.0)
- Turned off Bluetooth on nearby devices that have connected with band (e.g. phone, etc.)
- Put band into pairing mode, paired/connected from the OS GUI first and made sure the band was connected
- Modified example script with proper address substring  (looks like you're fine here)
- Ran `python3 buzz_a_buzz.py` and I think I had to put the band in pairing mode again to get it to work. (you're fine here)

Maybe try to follow my steps and let me know? Weird that for Bleak you got 0.11.0 and I got 0.10.0 in the install process.

**Comment by dhruvmsheth** [comment]
@GreatScott Bull's eye! This got my issue sorted. The only thing I had to do was run
```python
pip3 install bleak==0.10.0
```

Initially I got defaulted to bleak v0.11.0, which caused errors. The v0.10.0 works very well, with no latency even in virtual env. Thanks a lot! I'll be working on the Python SDK, so if I come across any issue, and get a solution, I'll submit a PR. Thanks!!
